# **Loading Dataset For Analysis**

In [2]:
import pandas as pd

train_df = pd.read_csv('Dataset/train.csv',encoding='latin-1')
train_df

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26
...,...,...,...,...,...,...,...,...,...,...
27476,4eac33d1c0,wish we could come see u on Denver husband l...,d lost,negative,night,31-45,Ghana,31072940,227540.0,137
27477,4f4c4fc327,I`ve wondered about rake to. The client has ...,", don`t force",negative,morning,46-60,Greece,10423054,128900.0,81
27478,f67aae2310,Yay good for both of you. Enjoy the break - y...,Yay good for both of you.,positive,noon,60-70,Grenada,112523,340.0,331
27479,ed167662a5,But it was worth it ****.,But it was worth it ****.,positive,night,70-100,Guatemala,17915568,107160.0,167
27480,6f7127d9d7,All this flirting going on - The ATG smiles...,All this flirting going on - The ATG smiles. Y...,neutral,morning,0-20,Guinea,13132795,246000.0,53

# **Convert labels into 0 & 1**

In [3]:
train_df.rename(columns={"sentiment": "label"}, inplace=True)
train_df["label"] = train_df["label"].replace({"negative": 0, "positive": 1})

In [4]:
train_df = train_df.drop(train_df[train_df["label"] == "neutral"].index)
train_df

,textID,text,selected_text,label,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,0,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,0,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,0,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",0,noon,60-70,Angola,32866272,1246700.0,26
6,6e0c6d75b1,2am feedings for the baby are fun when he is a...,fun,1,morning,0-20,Argentina,45195774,2736690.0,17
...,...,...,...,...,...,...,...,...,...,...
27475,b78ec00df5,enjoy ur night,enjoy,1,noon,21-30,Germany,83783942,348560.0,240
27476,4eac33d1c0,wish we could come see u on Denver husband l...,d lost,0,night,31-45,Ghana,31072940,227540.0,137
27477,4f4c4fc327,I`ve wondered about rake to. The client has ...,", don`t force",0,morning,46-60,Greece,10423054,128900.0,81
27478,f67aae2310,Yay good for both of you. Enjoy the break - y...,Yay good for both of you.,1,noon,60-70,Grenada,112523,340.0,331
27479,ed167662a5,But it was worth it ****.,But it was worth it ****.,1,night,70-100,Guatemala,17915568,107160.0,167

# **Download some files in zip format & convert into unzip**

In [5]:
!wget http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip

--2025-12-11 14:09:30--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 64:ff9b::ab40:4016, 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|64:ff9b::ab40:4016|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.1’

glove.6B.zip.1      100%[===================>] 822.24M  4.75MB/s    in 3m 17s

2025-12-11 14:12:49 (4.17 MB/s) - ‘glove.6B.zip.1’ saved [862182613/862182613]

In [ ]:
!unzip glove.6B.zip

Archive:  glove.6B.zip
replace glove.6B.50d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
import numpy as np

words = dict()

def add_to_dict(d, filename):
  with open(filename, 'r') as f:
    for line in f.readlines():
      line = line.split(' ')

      try:
        d[line[0]] = np.array(line[1:], dtype=float)
      except:
        continue

add_to_dict(words, 'glove.6B.50d.txt')
words

In [ ]:
len(words)

# **nltk Download some Required Data or Files**

In [ ]:
import nltk

nltk.download('wordnet')

In [ ]:
nltk.download('omw-1.4')
nltk.download('wordnet')

In [ ]:
tokenizer = nltk.RegexpTokenizer(r"\w+")

tokenizer.tokenize('@user when a father is dysfunctional and is')

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def message_to_token_list(s):
  tokens = tokenizer.tokenize(s)
  lowercased_tokens = [t.lower() for t in tokens]
  lemmatized_tokens = [lemmatizer.lemmatize(t) for t in lowercased_tokens]
  useful_tokens = [t for t in lemmatized_tokens if t in words]

  return useful_tokens

message_to_token_list('@user feet a fathers is dysfunctional and is')

In [ ]:
def message_to_word_vectors(message, word_dict=words):
  processed_list_of_tokens = message_to_token_list(message)

  vectors = []

  for token in processed_list_of_tokens:
    if token not in word_dict:
      continue

    token_vector = word_dict[token]
    vectors.append(token_vector)

  return np.array(vectors, dtype=float)

message_to_word_vectors('@user when a father is dysfunctional and is').shape

# **Data Split for Training**

In [ ]:
train_df = train_df.sample(frac=1, random_state=1)
train_df.reset_index(drop=True, inplace=True)

split_index_1 = int(len(train_df) * 0.7)
split_index_2 = int(len(train_df) * 0.85)

train_df, val_df, test_df = train_df[:split_index_1], train_df[split_index_1:split_index_2], train_df[split_index_2:]

len(train_df), len(val_df), len(test_df)

In [ ]:
test_df

In [17]:
def df_to_X_y(dff):
  y = dff['label'].to_numpy().astype(int)

  all_word_vector_sequences = []

  for message in dff['text']:
    message_as_vector_seq = message_to_word_vectors(message)

    if message_as_vector_seq.shape[0] == 0:
      message_as_vector_seq = np.zeros(shape=(1, 50))

    all_word_vector_sequences.append(message_as_vector_seq)

  return all_word_vector_sequences, y

In [18]:
train_df['text'] = train_df['text'].fillna('')
train_df['text'] = train_df['text'].astype(str)

# Now create X, y
X_train, y_train = df_to_X_y(train_df)
print(len(X_train), len(X_train[0]))

11454 12

In [19]:
print(len(X_train), len(X_train[2]))

11454 12

In [1]:
sequence_lengths = []

for i in range(len(X_train)):
  sequence_lengths.append(len(X_train[i]))

import matplotlib.pyplot as plt

plt.title("Sequence Length graph")
plt.hist(sequence_lengths)

NameError: name 'X_train' is not defined

In [21]:
pd.Series(sequence_lengths).describe()

count    11454.000000
mean        13.369391
std          6.966197
min          1.000000
25%          8.000000
50%         12.000000
75%         19.000000
max         34.000000
dtype: float64

In [70]:
from copy import deepcopy

def pad_X(X, desired_sequence_length=57):
  X_copy = deepcopy(X)

  for i, x in enumerate(X):
    x_seq_len = x.shape[0]
    sequence_length_difference = desired_sequence_length - x_seq_len

    pad = np.zeros(shape=(sequence_length_difference, 50))
    X_copy[i] = np.concatenate([x, pad])

  return np.array(X_copy).astype(float)

In [71]:
X_train = pad_X(X_train)

X_train.shape

(11454, 57, 50)

In [72]:
y_train.shape

(11454,)

In [73]:
X_val, y_val = df_to_X_y(val_df)
X_val = pad_X(X_val)

X_val.shape, y_val.shape

((2454, 57, 50), (2454,))

In [74]:
X_test, y_test = df_to_X_y(test_df)
X_test = pad_X(X_test)

X_test.shape, y_test.shape

((2455, 57, 50), (2455,))

# **model work on LSTM**

In [75]:
#Our Model using LSTM
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

model = Sequential([])

model.add(layers.Input(shape=(57, 50)))
model.add(layers.LSTM(64, return_sequences=True))
model.add(layers.Dropout(0.2))
model.add(layers.LSTM(64, return_sequences=True))
model.add(layers.Dropout(0.2))
model.add(layers.LSTM(64, return_sequences=True))
model.add(layers.Dropout(0.2))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid'))

# **It's summary of model**

In [76]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 57, 64)         │        29,440 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 57, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 57, 64)         │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 57, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 57, 64)         │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 57, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 3648)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │         3,649 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 99,137 (387.25 KB)

 Trainable params: 99,137 (387.25 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
#Saving our Model
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC
from tensorflow.keras.callbacks import ModelCheckpoint

cp = ModelCheckpoint('/content/tw.keras', save_best_only=True)
#Hyper-parameters of our model
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss=BinaryCrossentropy(),
              metrics=['accuracy', AUC(name='auc')])

In [78]:
frequencies = pd.value_counts(train_df['label'])
frequencies

/tmp/ipython-input-3931351302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  frequencies = pd.value_counts(train_df['label'])

label
1    5971
0    5483
Name: count, dtype: int64

In [79]:
weights = {0: frequencies.sum() / frequencies[0], 1: frequencies.sum() / frequencies[1]}
weights

{0: np.float64(2.0890023709648005), 1: np.float64(1.9182716462904037)}

# **Train model through 49 epoches but you are use early stopping**

In [80]:
#Fitiing our training our model
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=49, callbacks=[cp], class_weight=weights)

Epoch 1/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.6030 - auc: 0.6407 - loss: 1.3011 - val_accuracy: 0.7620 - val_auc: 0.8422 - val_loss: 0.5002
Epoch 2/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.7686 - auc: 0.8462 - loss: 0.9727 - val_accuracy: 0.7722 - val_auc: 0.8629 - val_loss: 0.4751
Epoch 3/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.7873 - auc: 0.8654 - loss: 0.9166 - val_accuracy: 0.7869 - val_auc: 0.8738 - val_loss: 0.4525
Epoch 4/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.7913 - auc: 0.8734 - loss: 0.8920 - val_accuracy: 0.7967 - val_auc: 0.8810 - val_loss: 0.4362
Epoch 5/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.7962 - auc: 0.8788 - loss: 0.8717 - val_accuracy: 0.8011 - val_auc: 0.8865 - val_loss: 0.4242
Epoch 6/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.8123 - auc: 0.8932 - loss: 0.8242 - val_accuracy: 0.8093 - val_auc: 0.8911 - val_loss: 0.4179
Epoch 7/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8105 - auc: 0.8933 - loss: 0.8236 - val_accuracy: 0.8101 - val_auc: 0.8950 - val_loss: 0.4104
Epoch 8/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8207 - auc: 0.9029 - loss: 0.7855 - val_accuracy: 0.8199 - val_auc: 0.8986 - val_loss: 0.4035
Epoch 9/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8155 - auc: 0.8986 - loss: 0.8013 - val_accuracy: 0.8195 - val_auc: 0.9027 - val_loss: 0.4003
Epoch 10/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8287 - auc: 0.9075 - loss: 0.7696 - val_accuracy: 0.8195 - val_auc: 0.9047 - val_loss: 0.3966
Epoch 11/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8332 - auc: 0.9133 - loss: 0.7455 - val_accuracy: 0.8223 - val_auc: 0.9094 - val_loss: 0.3939
Epoch 12/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8405 - auc: 0.9197 - loss: 0.7185 - val_accuracy: 0.8231 - val_auc: 0.9100 - val_loss: 0.3855
Epoch 13/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8464 - auc: 0.9225 - loss: 0.7064 - val_accuracy: 0.8346 - val_auc: 0.9125 - val_loss: 0.3842
Epoch 14/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.8483 - auc: 0.9251 - loss: 0.6938 - val_accuracy: 0.8390 - val_auc: 0.9126 - val_loss: 0.3753
Epoch 15/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8495 - auc: 0.9249 - loss: 0.6907 - val_accuracy: 0.8333 - val_auc: 0.9157 - val_loss: 0.3707
Epoch 16/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8567 - auc: 0.9310 - loss: 0.6655 - val_accuracy: 0.8333 - val_auc: 0.9171 - val_loss: 0.3789
Epoch 17/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8630 - auc: 0.9368 - loss: 0.6394 - val_accuracy: 0.8427 - val_auc: 0.9187 - val_loss: 0.3616
Epoch 18/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8648 - auc: 0.9355 - loss: 0.6437 - val_accuracy: 0.8460 - val_auc: 0.9185 - val_loss: 0.3623
Epoch 19/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8689 - auc: 0.9369 - loss: 0.6395 - val_accuracy: 0.8468 - val_auc: 0.9197 - val_loss: 0.3660
Epoch 20/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8660 - auc: 0.9360 - loss: 0.6433 - val_accuracy: 0.8488 - val_auc: 0.9203 - val_loss: 0.3621
Epoch 21/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.8661 - auc: 0.9361 - loss: 0.6447 - val_accuracy: 0.8390 - val_auc: 0.9208 - val_loss: 0.3672
Epoch 22/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8789 - auc: 0.9447 - loss: 0.5948 - val_accuracy: 0.8227 - val_auc: 0.9223 - val_loss: 0.3894
Epoch 23/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.8675 - auc: 0.9391 - loss: 0.6311 - val_accuracy: 0.8500 - val_auc: 0.9224 - val_loss: 0.3545
Epoch 24/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8621 - auc: 0.9371 - loss: 0.6376 - val_accuracy: 0.8509 - val_auc: 0.9229 - val_loss: 0.3680
Epoch 25/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.8658 - auc: 0.9365 - loss: 0.6403 - val_accuracy: 0.8488 - val_auc: 0.9235 - val_loss: 0.3547
Epoch 26/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8753 - auc: 0.9434 - loss: 0.6046 - val_accuracy: 0.8496 - val_auc: 0.9240 - val_loss: 0.3531
Epoch 27/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8749 - auc: 0.9454 - loss: 0.5955 - val_accuracy: 0.8476 - val_auc: 0.9243 - val_loss: 0.3664
Epoch 28/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8806 - auc: 0.9475 - loss: 0.5815 - val_accuracy: 0.8504 - val_auc: 0.9249 - val_loss: 0.3500
Epoch 29/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.8777 - auc: 0.9477 - loss: 0.5808 - val_accuracy: 0.8472 - val_auc: 0.9225 - val_loss: 0.3657
Epoch 30/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.8851 - auc: 0.9526 - loss: 0.5512 - val_accuracy: 0.8504 - val_auc: 0.9238 - val_loss: 0.3540
Epoch 31/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8740 - auc: 0.9437 - loss: 0.6003 - val_accuracy: 0.8541 - val_auc: 0.9255 - val_loss: 0.3579
Epoch 32/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8776 - auc: 0.9477 - loss: 0.5781 - val_accuracy: 0.8553 - val_auc: 0.9251 - val_loss: 0.3655
Epoch 33/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8827 - auc: 0.9517 - loss: 0.5574 - val_accuracy: 0.8517 - val_auc: 0.9260 - val_loss: 0.3511
Epoch 34/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8824 - auc: 0.9518 - loss: 0.5611 - val_accuracy: 0.8545 - val_auc: 0.9255 - val_loss: 0.3585
Epoch 35/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8731 - auc: 0.9449 - loss: 0.5942 - val_accuracy: 0.8435 - val_auc: 0.9270 - val_loss: 0.3639
Epoch 36/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.8819 - auc: 0.9513 - loss: 0.5605 - val_accuracy: 0.8509 - val_auc: 0.9262 - val_loss: 0.3772
Epoch 37/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8934 - auc: 0.9547 - loss: 0.5385 - val_accuracy: 0.8521 - val_auc: 0.9261 - val_loss: 0.3458
Epoch 38/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.8943 - auc: 0.9575 - loss: 0.5266 - val_accuracy: 0.8582 - val_auc: 0.9267 - val_loss: 0.3566
Epoch 39/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8978 - auc: 0.9605 - loss: 0.5065 - val_accuracy: 0.8562 - val_auc: 0.9275 - val_loss: 0.3495
Epoch 40/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8924 - auc: 0.9572 - loss: 0.5238 - val_accuracy: 0.8419 - val_auc: 0.9233 - val_loss: 0.3828
Epoch 41/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8869 - auc: 0.9569 - loss: 0.5310 - val_accuracy: 0.8488 - val_auc: 0.9255 - val_loss: 0.3672
Epoch 42/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8919 - auc: 0.9550 - loss: 0.5354 - val_accuracy: 0.8488 - val_auc: 0.9264 - val_loss: 0.3665
Epoch 43/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.9017 - auc: 0.9616 - loss: 0.4962 - val_accuracy: 0.8517 - val_auc: 0.9265 - val_loss: 0.3695
Epoch 44/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8928 - auc: 0.9575 - loss: 0.5194 - val_accuracy: 0.8557 - val_auc: 0.9267 - val_loss: 0.3623
Epoch 45/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8942 - auc: 0.9583 - loss: 0.5177 - val_accuracy: 0.8553 - val_auc: 0.9273 - val_loss: 0.3527
Epoch 46/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.9002 - auc: 0.9611 - loss: 0.4977 - val_accuracy: 0.8541 - val_auc: 0.9275 - val_loss: 0.3591
Epoch 47/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.8993 - auc: 0.9631 - loss: 0.4866 - val_accuracy: 0.8468 - val_auc: 0.9246 - val_loss: 0.3907
Epoch 48/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.8947 - auc: 0.9582 - loss: 0.5148 - val_accuracy: 0.8529 - val_auc: 0.9268 - val_loss: 0.3795
Epoch 49/49
358/358 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.9060 - auc: 0.9656 - loss: 0.4688 - val_accuracy: 0.8509 - val_auc: 0.9268 - val_loss: 0.3770

In [81]:
from tensorflow.keras.models import load_model

best_model = load_model('/content/tw.keras')

In [82]:

test_predictions = (best_model.predict(X_test) > 0.5).astype(int)

from sklearn.metrics import classification_report

print(classification_report(y_test, test_predictions))

77/77 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
              precision    recall  f1-score   support

           0       0.82      0.85      0.84      1154
           1       0.86      0.84      0.85      1301

    accuracy                           0.84      2455
   macro avg       0.84      0.84      0.84      2455
weighted avg       0.84      0.84      0.84      2455

# **Test**

In [85]:
a='Recession hit Veronique Branquinho, she has to quit her company, such a shame!'
b=message_to_token_list(a)
print(b)
c=message_to_word_vectors(a, word_dict=words)
print(c)
l=1
all_word_vector_sequences = []

if c.shape[0] == 0:
  c = np.zeros(shape=(1, 50))

all_word_vector_sequences.append(c)
d=pad_X(all_word_vector_sequences, desired_sequence_length=57)
print(best_model.predict(d))
t_predictions = (best_model.predict(d) > 0.5).astype(int)


print('The Sentiment of this tweet is: ',t_predictions)

['recession', 'hit', 'veronique', 'branquinho', 'she', 'ha', 'to', 'quit', 'her', 'company', 'such', 'a', 'shame']
[[ 1.8179e-01 -7.5381e-01  5.8120e-01 -1.0506e+00 -8.1497e-01  2.8252e-01
  -2.8160e-01 -1.6284e-02  7.5189e-02 -1.8392e-01  1.7294e-02 -3.3048e-01
  -7.8017e-01  4.7358e-01  1.0580e+00  8.4421e-01 -2.1532e-01 -8.3700e-01
  -1.7485e-01  3.1259e-01  8.7176e-02 -1.1799e+00 -4.8552e-01 -5.5888e-01
   5.1402e-01 -1.2151e+00 -5.0250e-01  4.7488e-01  8.5208e-01  1.7429e+00
   2.3028e+00  5.0215e-01  1.2699e+00  1.5825e-01 -9.3648e-01 -5.8294e-01
  -1.1013e+00 -3.2265e-01  5.3048e-01 -1.3961e+00 -1.9727e+00 -2.2009e-01
   4.7897e-01 -2.6444e-01  2.0521e-01  2.7641e-01  1.0516e+00  4.2095e-01
   3.4474e-01 -2.7933e-02]
 [-4.1659e-01 -4.7596e-01  9.5744e-01  2.7019e-01  1.7657e-01  2.4828e-01
  -1.2987e+00  5.3851e-01  3.5336e-01  5.8221e-01 -3.3079e-01 -5.9680e-01
  -9.7055e-01  7.2084e-01  4.9463e-01 -8.3398e-01  1.2236e-01 -3.7237e-01
  -1.4546e+00  4.1384e-01 -3.6311e-01  2.2020e-01  5.7482e-02 -2.4951e-01
   3.7654e-01 -1.3061e+00  2.2596e-01  4.7510e-01  1.2860e+00 -6.2643e-01
   3.4058e+00  1.8436e-01  1.2656e+00  1.0741e+00  3.0260e-01  3.1395e-01
   3.3683e-01 -3.1895e-01  3.1912e-01  3.7919e-01 -1.1652e+00  9.4625e-01
  -4.4854e-02 -1.0779e+00 -1.6669e-01  1.1604e-01 -1.1983e-01 -2.3663e-01
   2.9088e-01  1.1071e-01]
 [ 2.5406e-01  1.5724e-01 -2.5493e-01 -1.4410e-01  4.9782e-01 -2.1650e-01
   9.5952e-03  3.2772e-01  1.0235e+00 -1.8365e-01  4.7726e-01  3.4982e-01
  -8.6135e-01 -4.2507e-01  3.5826e-01 -7.5079e-01 -2.2315e-01 -4.8919e-01
   6.2154e-01 -4.3639e-01 -1.2189e-01  9.1372e-01  9.4915e-02 -1.2045e+00
  -4.5292e-02  3.4572e-01 -5.1747e-01  4.3248e-01 -6.9015e-02 -7.6508e-02
  -1.4588e+00 -1.4179e-01  2.9791e-01  6.3597e-01 -1.3038e-01 -8.5750e-01
  -2.3863e-01  6.5100e-01  9.7012e-01  5.6780e-01  1.7174e-01 -9.7337e-02
   1.3832e+00 -8.8343e-01  3.0145e-01 -1.3192e+00 -5.2970e-01 -9.3344e-02
   3.8895e-01  5.0601e-01]
 [ 4.2913e-01 -3.1390e-01 -2.8853e-01 -5.9268e-01 -8.1233e-02  4.9795e-03
  -2.6980e-01  4.9550e-01  1.3729e+00  5.6722e-01  8.4390e-01  3.7086e-01
   5.4844e-02 -5.7477e-02 -1.4398e-01 -9.7660e-01 -2.6622e-01 -6.7163e-01
   6.2104e-01 -3.4597e-01 -5.6759e-01  5.7061e-01 -3.5554e-01 -3.9939e-01
   6.4609e-01  1.1396e+00  1.3843e-01  1.9405e-01 -2.2361e-02 -2.4440e-01
  -1.7299e+00  1.3376e-01  7.8869e-01  3.5104e-01  1.2237e-01 -3.4360e-01
  -3.5252e-01  7.9730e-01 -5.7281e-02  3.4732e-03  5.8603e-01 -5.7402e-01
   1.2847e+00 -2.8443e-01 -2.3074e-01 -1.1600e+00  5.4990e-01  3.0277e-01
  -1.8171e-02  1.9145e-01]
 [ 6.0382e-02  3.7821e-01 -7.5142e-01 -7.2159e-01  5.8648e-01  7.9126e-01
  -7.2947e-01  6.8248e-01 -1.2999e-01 -2.2988e-01  1.1595e-01  2.2427e-01
  -4.4679e-01 -1.1515e-01  1.0334e+00 -8.8019e-02 -7.8531e-01  3.4305e-01
  -1.1457e-01 -1.1905e-01  4.5883e-01  1.6333e+00  6.8546e-01  2.2308e-01
   1.0099e+00 -2.6332e+00 -5.2128e-01  2.5665e-01  2.3468e-02 -8.2616e-01
   3.1084e+00  2.7219e-01 -2.9227e-01 -4.7259e-01 -1.2297e-01 -1.3545e-01
   1.1192e-01  8.6438e-01  3.3121e-01 -9.6616e-01 -4.4785e-02 -6.6740e-02
   3.0367e-03 -3.3905e-01  1.7784e-02 -5.8499e-01 -5.0140e-03 -1.2570e+00
  -6.0723e-02  4.2247e-01]
 [ 3.2279e-01  1.0339e+00  6.8736e-01  3.3264e-01 -5.3446e-01 -1.2597e+00
   2.9752e-01 -1.0556e+00 -3.8863e-01  2.3860e-01 -5.0496e-01 -5.2201e-01
   9.3708e-01 -1.1434e+00  6.4355e-01 -1.3610e-01  9.8134e-01  8.6675e-01
   4.3259e-01  1.3294e+00 -1.2559e+00 -5.1960e-01  1.1926e+00 -4.0755e-01
   4.2485e-01  3.2406e-01 -4.9671e-02  8.1369e-01  1.0967e-01 -1.9915e-01
   1.8513e+00 -9.5185e-01  3.2119e-01  1.6937e+00 -2.2977e-01 -1.4122e-01
   3.5369e-01  4.3029e-01  3.8096e-01  6.3528e-01 -4.2678e-01  1.5050e-01
   6.4915e-01 -6.7914e-01  3.5834e-01 -1.9164e+00 -7.2465e-01 -7.2028e-01
   1.9126e-01  7.3216e-01]
 [ 6.8047e-01 -3.9263e-02  3.0186e-01 -1.7792e-01  4.2962e-01  3.2246e-02
  -4.1376e-01  1.3228e-01 -2.9847e-01 -8.5253e-02  1.7118e-01  2.2419e-01
  -1.0046e-01 -4.3653e-01  3.3418e-01  6.7846e-01  5.7204e-02 -3.4448e-01
  -4.2785e-01 -4.3275e-01  5.5963e-01  1.0032e-01  1.8677e-01 -2.6854e-01
   3.7334e-02 -2.0932e+00  2.2171e-01 -3.9868e-01  2.0912e-01 -5.5725e-01
   3.8826e+00  4.7466e-01 -9.5658e-01 -3.7788e-01  2.0869e-01 -3.2752e-01
   1.2751e-01  8.8359e-02  1.6351e-01 -2.1634e-01 -9.4375e-02  1.8324e-02
   2.1048e-01 -3.0880e-02 -1.9722e-01  8.2279e-02 -9.4340e-02 -7.3297e-02
  -6.4699e-02 -2.6044e-01]
 [-3.4665e-01 -6.1115e-01  1.1695e-01 -5.6910e-01 -5.4018e-01 -8.3589e-02
  -4.8692e-01  1.0036e+00 -7.6362e-01 -1.5050e-01  2.7196e-01  2.0035e-01
  -1.2507e+00  5.6309e-02  9.8568e-01  6.6344e-01  5.9202e-02  3.7088e-01
   3.9904e-01 -1.2548e-01  2.0121e-01  7.5254e-01  5.5030e-01  3.5573e-01
  -6.6738e-02 -1.7729e+00  8.4616e-01 -2.4803e-01 -3.0495e-01  6.3516e-01
   1.7474e+00  7.5418e-01 -1.0441e+00  1.5498e-01 -4.8388e-01 -6.2593e-02
   2.5791e-01  8.9859e-02  4.8763e-01 -6.8871e-01 -4.0271e-01  9.1483e-03
  -8.8720e-01  1.8800e-01  4.8919e-01 -9.4819e-02 -7.8981e-01  6.2779e-02
  -1.7709e-01  2.7109e-01]
 [ 1.3403e-01  8.9178e-01 -7.6761e-01 -6.4184e-01  8.6204e-01  1.3122e+00
  -6.4018e-01  8.2067e-01  3.2783e-01  2.1457e-02 -9.5194e-02  4.0825e-01
  -6.3602e-01 -1.8275e-02  6.9708e-01 -2.9531e-01 -1.1912e+00 -2.3897e-01
   3.4341e-01 -3.3196e-01  2.3702e-01  1.8364e+00  1.2295e-01 -1.8624e-01
   8.6503e-01 -2.6360e+00 -7.7910e-01  2.0300e-01  1.8985e-01 -7.9897e-01
   2.9882e+00  4.4336e-01 -2.8367e-01 -1.9588e-01  6.1875e-02  3.8558e-01
  -2.7622e-02  7.1847e-01  1.7156e-01 -1.2168e+00  8.1636e-02  1.7293e-01
  -3.1718e-01 -3.7039e-01  1.8977e-01 -8.9175e-01  1.8492e-01 -1.6251e+00
   3.9134e-02 -1.0279e-01]
 [ 6.2583e-01 -5.7703e-01  4.1163e-01  8.6812e-01 -8.3097e-02  2.6555e-01
  -1.4800e+00 -3.8792e-01  4.2727e-01  1.1680e-01  7.8390e-01  8.1352e-01
  -7.8763e-01 -6.5440e-01 -9.9214e-02  2.0658e-01 -7.3315e-01  8.6418e-01
  -2.6917e-01 -9.3792e-01  1.9190e+00 -1.7473e-01 -6.1905e-01 -5.0350e-01
  -9.3410e-01 -1.6755e+00 -7.9399e-01 -3.2003e-01 -6.7678e-02 -1.2344e-01
   3.2909e+00 -4.3151e-01  3.8790e-01  3.8733e-01 -1.8419e-02 -9.8191e-01
  -5.3189e-01  3.9866e-01  8.9452e-01 -4.0963e-01  5.8922e-01 -5.2377e-01
   2.7893e-01 -2.5766e-01 -3.0457e-01 -6.6305e-02 -1.1221e+00  2.1582e-01
  -1.5586e-01  6.4018e-01]
 [ 6.1012e-01  3.3512e-01 -5.3499e-01  3.6139e-01 -3.9866e-01  7.0627e-01
  -1.8699e-01 -7.7246e-01 -3.4846e-02  6.6066e-01  8.2030e-02  7.9279e-01
   5.7070e-02 -1.8946e-01  1.7522e-01  1.3938e-01  3.1923e-01 -7.5718e-02
   1.2428e-01 -1.0630e+00  2.8938e-01 -2.9671e-01  1.1209e-01  7.3609e-02
  -2.2206e-01 -1.2550e+00 -1.0307e+00 -4.6799e-01  2.3850e-01 -2.1157e-01
   3.8345e+00  1.6838e-01  1.8882e-02 -9.8550e-01  9.6963e-02  2.6432e-01
  -1.8384e-01 -2.2391e-01 -5.3277e-01  4.1996e-01 -1.1031e-01  4.2182e-01
   2.7344e-01  4.9600e-01  7.9203e-01  2.4127e-01 -4.1725e-01  2.8288e-01
  -2.8283e-01  8.4747e-02]
 [ 2.1705e-01  4.6515e-01 -4.6757e-01  1.0082e-01  1.0135e+00  7.4845e-01
  -5.3104e-01 -2.6256e-01  1.6812e-01  1.3182e-01 -2.4909e-01 -4.4185e-01
  -2.1739e-01  5.1004e-01  1.3448e-01 -4.3141e-01 -3.1230e-02  2.0674e-01
  -7.8138e-01 -2.0148e-01 -9.7401e-02  1.6088e-01 -6.1836e-01 -1.8504e-01
  -1.2461e-01 -2.2526e+00 -2.2321e-01  5.0430e-01  3.2257e-01  1.5313e-01
   3.9636e+00 -7.1365e-01 -6.7012e-01  2.8388e-01  2.1738e-01  1.4433e-01
   2.5926e-01  2.3434e-01  4.2740e-01 -4.4451e-01  1.3813e-01  3.6973e-01
  -6.4289e-01  2.4142e-02 -3.9315e-02 -2.6037e-01  1.2017e-01 -4.3782e-02
   4.1013e-01  1.7960e-01]
 [-4.1604e-01  5.8899e-01 -2.9203e-01 -7.1379e-01  4.4346e-01  1.5361e-01
   9.4146e-01  5.0782e-01 -1.6508e-01  5.3246e-01 -2.6613e-01  3.9842e-01
  -5.9873e-01 -5.0793e-01  1.0185e+00 -1.4212e-01  2.6814e-01  1.6927e-01
   2.8519e-01 -3.7620e-01 -4.1834e-01  5.1464e-01  1.7179e-01 -7.8859e-02
   7.2538e-01 -1.5551e+00 -1.1505e+00  6.0445e-01  7.9952e-01 -4.3377e-01
   1.1156e+00  1.1114e+00  2.2024e-02 -4.6275e-01 -1.5186e+00  5.9752e-02
   3.3848e-01 -1.1742e+00  2.6871e-01 -3.7709e-01  1.8269e-02 -2.4594e-01
  -2.6319e-01  3.2642e-01  3.3824e-01  4.0975e-01 -9.0466e-01 -1.7072e-01
   2.1578e-01 -5.6297e-01]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.04297088]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
The Sentiment of this tweet is:  [[0]]

In [86]:
#Use this function if you want remove unneeded symbols
import re

def text_cleaning(text):
  text = re.sub(r'@[A-Za-z0-9]+', '', text)     # removing @mentions
  text = re.sub(r'@[A-Za-zA-Z0-9]+', '', text)  # removing @mentions
  text = re.sub(r'@[A-Za-z]+', '', text)        # removing @mentions
  text = re.sub(r'@[-)]+', '', text)            # removing @mentions
  text = re.sub(r'#', '', text )                # removing '#' sign
  text = re.sub(r'RT[\s]+', '', text)           # removing RT
  text = re.sub(r'https?\/\/\S+', '', text)     # removing the hyper link
  text = re.sub(r'&[a-z;]+', '', text)          # removing '>'

  return text

# applying the text cleaning function on tweets
train_df['selected_text'] = train_df['selected_text'].apply(text_cleaning)
train_df.head(10)

,textID,text,selected_text,label,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,733d30d2f7,Haha. It`s pretty good they`re making somethi...,good,1,morning,0-20,Ukraine,43733762,579320.0,75
1,42e9dce94a,Happy Mama`s day to all mothers,Happy,1,noon,60-70,Zambia,18383955,743390.0,25
2,c5990861b8,I`m sure you`d consider it if they offerred t...,I`m sure you`d consider,1,noon,21-30,Azerbaijan,10139177,82658.0,123
3,f9483e7dc1,Sometimes the things you say hurt the ones you...,hurt,0,noon,21-30,Côte d'Ivoire,26378274,318000.0,83
4,3d0896ec67,you can put a saucepan full of water on the c...,...indian style scrabbled are the best!,1,morning,46-60,Rwanda,12952218,24670.0,525
5,fcdbdfce85,Thanks madam.. you`re lucky coz you had a won...,you had a wonderful dog.. and sooo cute...,1,night,31-45,Netherlands,17134872,33720.0,508
6,7caac2808c,Happy Star Wars Day!!!,Happy Star Wars Day!!!,1,morning,46-60,South Korea,51269185,97230.0,527
7,5.20E+45,"can`t wait to see `Transformers 2`.. C`me on, ...",Yippiee!,1,night,70-100,Barbados,287375,430.0,668
8,bfcac206a0,ok nevermind. photo was set to private. sorry.,sorry.,0,night,70-100,Slovenia,2078938,20140.0,103
9,ddbdb89b1b,Going to bed. Goodnight! x,Going to bed. Goodnight! x,1,morning,0-20,Ukraine,43733762,579320.0,75